[2024-11-30 17:28:22,365] [DEBUG] [main.py:11] This message should go to the log file
[2024-11-30 17:28:22,365] [INFO] [main.py:12] So should this
[2024-11-30 17:28:22,365] [WARNING] [main.py:13] And this, too
[2024-11-30 17:28:22,365] [ERROR] [main.py:14] And non-ASCII stuff, too, like Øresund and Malmö
[2024-11-30 17:28:22,368] [ERROR] [main.py:23] mainでエラーを捕捉した!
Traceback (most recent call last):
  File "/Users/dgmr2/programming/debugger/Notebook/logger/use-yaml/main.py", line 19, in main
    result = culc_div(1, 0)
  File "/Users/dgmr2/programming/debugger/Notebook/logger/use-yaml/mymodule.py", line 23, in culc_div
    result = num1 / num2
             ~~~~~^~~~~~
ZeroDivisionError: division by zero
