[2024-11-30 17:28:22,365] [INFO] [mymodule.py:8] This is test_func1
[2024-11-30 17:28:22,365] [DEBUG] [mymodule.py:9] a
[2024-11-30 17:28:22,365] [INFO] [mymodule.py:14] This is test_func2
[2024-11-30 17:28:22,365] [DEBUG] [mymodule.py:15] a
[2024-11-30 17:28:22,365] [DEBUG] [mymodule.py:20] num1:1
[2024-11-30 17:28:22,365] [DEBUG] [mymodule.py:21] num2:0
[2024-11-30 17:28:22,365] [ERROR] [mymodule.py:27] mymodoleでエラーを捕捉した!
Traceback (most recent call last):
  File "/Users/dgmr2/programming/debugger/Notebook/logger/use-yaml/mymodule.py", line 23, in culc_div
    result = num1 / num2
             ~~~~~^~~~~~
ZeroDivisionError: division by zero
